version: "3.8"
services:
  app:
    build:
      context: .
    env_file:
      - .env
    networks:
      - kafka_network
    restart: always
#    environment:
#      KAFKA_PARTITION: "${KAFKA_PARTITION}"
    deploy:
      mode: replicated
      replicas: 4
networks:
  kafka_network:
    external: true
#  db:
#    external: true

